### ISSUE TITLE
Broken with Java 11

### ISSUE THREAD

**Issue by emil0r** [TimoFreiberg/bultitude#9] opened 2019-10-24 19:19 UTC
Using bultitude on Java 11 gives back nothing when looking for namespaces on the classpath. Tried to look into it, but my java chops are a bit too weak to even know where to begin as RT/baseLoader is what is used as loader for dynapath.

```clojure
user => (require '[bultitude.core :as b])
nil
user => (take 10 (b/namespaces-on-classpath))
()
```

**Comment by TimoFreiberg** [comment] 2019-10-25 07:10
I'm quite sure this is caused by the same error that caused the CI build for https://github.com/TimoFreiberg/bultitude/pull/7 to fail, which is caused by https://github.com/tobias/dynapath/issues/12.

**Comment by TimoFreiberg** [comment] 2019-10-25 08:11
I just tried replacing `dynapath` with `org.clojure/java.classpath`. It seems like this issue was fixed there.
I'm also gonna check if `bultitude` can be replaced with `org.clojure/tools.namespace` - I would like to make this library obsolete ;)

**Comment by TimoFreiberg** [comment] 2019-10-25 10:28
This should be fixed with https://github.com/TimoFreiberg/bultitude/pull/10

**Comment by emil0r** [comment] 2019-10-25 15:48
Hmm... sadly not on my machine :p. Anything you would want me to do to check?

```
java -version                                                                                                                                            [17:42:38]
openjdk version "11.0.1" 2018-10-16
OpenJDK Runtime Environment 18.9 (build 11.0.1+13)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.1+13, mixed mode)
```

**Comment by emil0r** [comment] 2019-10-25 15:49
It's a bit weird though. All the tests pass with `lein test`. Running a manual test in the REPL doesn't work as it's supposed to.

**Comment by emil0r** [comment] 2019-10-25 21:13
clj repl with deps.edn works, whereas lein repl does not work.

**Comment by emil0r** [comment] 2019-10-25 21:38
Found the cause of the fault. Something in cider/cider-nrepl changes the classpath to only include `"/Library/Java/JavaVirtualMachines/openjdk-11.0.1.jdk/Contents/Home/lib/src.zip"`

**Comment by TimoFreiberg** [comment] 2019-10-26 06:28
Oh man. I have no idea what to do about this.

**Comment by emil0r** [comment] 2019-10-26 19:37
Well, for my use case I wanted to dynamically load namespaces under a given path. I've found a sort of workaround where I use the classpath/system-classpath to get what I want. I'm somewhat unsure how stable this is and if it'll work in every environment this used to work in. But for me this is good enough for the time being. Thank you for your help, it allowed me to move forward :).

```clojure
(defn load-views-ns [& ns-syms]
  (doseq [sym ns-syms
          f (namespaces-on-classpath
             :prefix (name sym)
             :classpath (cp/system-classpath))]
    (require f)))
```

**Comment by TimoFreiberg** [comment] 2021-03-21 14:59
Closing this since it sounds like the workaround is fine so far. Feel free to reopen if this becomes an issue again

**Closed as completed by TimoFreiberg** 2021-03-21 14:59 UTC
